server.port: 8080
server.compression.enabled: true
server.compression.mime-types: application/json,text/html,text/xml,text/plain,application/javascript,text/css

APP_NAME: dolly
APP_VERSION: ${application.version}

#### APP DB ####
? app.datasource.onsHosts

springfox:
  documentation:
    swagger:
      v2:
        path: /internal/swagger-spec

dolly:
  api:
    v1:
      name: Dolly V2.0
      description: Dolly er verktøyet som kloner GDPR testdata til ønsket miljø. </br>
               Opprett fiktive testpersoner med arbeidsforhold, inntekter, sykemelding og annet i hht testbehov.
      version: Versjon 1
      header:
        nav-consumer-id: Navn på applikasjon som gjør kallet
        nav-call-id: Unik identifikator, typisk UUID (128 bit)

spring:
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b/v2.0
          #The client_id of this application
          accepted-audience: ${client.id}, api://${client.id}

oracle:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver

management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /internal
      exposure.include: prometheus,heapdump
      path-mapping.prometheus: metrics
  endpoint:
    prometheus.enabled: true
    heapdump.enabled: true
  metrics.export:
    prometheus.enabled: true