server.port: 8080
server.compression.enabled: true
server.compression.mime-types: application/json,text/html,text/xml,text/plain,application/javascript,text/css

APP_NAME: dolly
APP_VERSION: ${application.version}

#### APP DB ####
? app.datasource.onsHosts

#### NEW FREG-SECURITY #####
freg.security.oidc.auth:
  securedPath: /**
  ignoredPaths: /internal/**,/api,/sysdoc/**,/swagger-ui.html,/swagger-resources/**,/swagger/**,/webjars/**

springfox:
  documentation:
    swagger:
      v2:
        path: /internal/swagger-spec

providers:
  tpsf:
    url: http://localhost:8050
  sigrun:
    url: http://localhost:8040
  aaregdata:
    url: https://testnorge-aareg.nais.preprod.local/api


### CORS ###
dolly.security.cors.origins: http://localhost:3050,http://localhost:3000,http://localhost:8020,http://localhost:8080

dolly:
  api:
    v1:
      name: API versjon 1
      description: Dolly er en kloningsklient for NAVs personopplysning. Bruk den til å opprette fiktive testpersoner med fiktive inntekter og arbeidsforhold.
      header:
        nav-consumer-id: En ID for systemet som gjør kallet, som regel servicebrukeren til applikasjonen.
        nav-call-id: En ID som identifiserer kallkjeden som dette kallet er en del av.

spring:
  main:
    allow-bean-definition-overriding: true


management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /internal
      exposure.include: prometheus,heapdump
      path-mapping.prometheus: metrics
  endpoint:
    prometheus.enabled: true
    heapdump.enabled: true
  metrics.export:
    prometheus.enabled: true