#Dev config
POST_LOGOUT_REDIRECT_URI: http://dolly-frontend-dev.dolly.svc.cluster.local/login
REDIS_HOST: dolly-dev-redis-session.dolly.svc.cluster.local

spring:
  redis:
    host: ${REDIS_HOST}
    port: 6379
  security:
    oauth2:
      resourceserver:
        idporten:
          issuer-uri: ${IDPORTEN_ISSUER_DEV_URI}
        aad:
          issuer-uri: ${AAD_ISSUER_URI}/v2.0
          jwk-set-uri: ${AAD_ISSUER_URI}/discovery/v2.0/keys
          accepted-audience: ${azure.app.client.id}, api://${azure.app.client.id}
        tokenx:
          issuer-uri: https://tokendings.dev-gcp.nais.io
          jwk-set-uri: https://tokendings.dev-gcp.nais.io/jwks

consumers:
  # Konsumenter for dev-milj√∏
  tps-forvalteren-proxy:
    name: tps-forvalteren-dev-proxy
    url: https://tps-forvalteren-dev-proxy.dev-fss-pub.nais.io
  dolly-backend:
    name: dolly-backend-dev
    url: https://dolly-backend-dev.dev.intern.nav.no
  testnorge-profil-api:
    name: testnorge-profil-api-dev
    url: http://testnorge-profil-api-dev.dolly.svc.cluster.local
  testnav-varslinger-service:
    name: testnav-varslinger-service-dev
    url: http://testnav-varslinger-service-dev.dolly.svc.cluster.local
  testnav-person-organisasjon-tilgang-service:
    name: testnav-person-organisasjon-tilgang-service-dev
    url: http://testnav-person-organisasjon-tilgang-service-dev.dolly.svc.cluster.local
  testnav-bruker-service:
    name: testnav-bruker-service-dev
    url: http://testnav-bruker-service-dev.dolly.svc.cluster.local
  testnav-pdl-forvalter:
    name: testnav-pdl-forvalter-dev
    url: http://testnav-pdl-forvalter-dev.dolly.svc.cluster.local