AAD_ISSUER_URI: https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b

database:
  aareg:
    username: ${AAREG_DB_USERNAME}
    password: ${AAREG_DB_PASSWORD}
    url: ${AAREG_DB_URL}

spring:
  security:
    oauth2:
      resourceserver:
        aad:
          issuer-uri: ${AAD_ISSUER_URI}/v2.0
          jwk-set-uri: ${AAD_ISSUER_URI}/discovery/v2.0/keys
          accepted-audience: ${azure.app.client.id}, api://${azure.app.client.id}
        tokenx:
          issuer-uri: https://tokendings.dev-gcp.nais.io
          jwk-set-uri: https://tokendings.dev-gcp.nais.io/jwks
          accepted-audience: dev-fss:dolly:testnorge-arbeidsforhold-export-api
  application:
    version: application.version.todo #TODO Finn ut hvordan denne kan settes fra gradle
    name: testnorge-arbeidsforhold-export-api
    description: Api for Ã¥ eksportere arbeidsforhold.