apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dolly-frontend
  namespace: dolly
  labels:
    team: dolly
spec:
  webproxy: true
  azure:
    application:
      enabled: true
      replyURLs:
        - https://dolly.dev.intern.nav.no/login/oauth2/code/aad
        - https://dolly-frontend.dev.adeo.no/login/oauth2/code/aad
        - https://dolly.nais.preprod.local/login/oauth2/code/aad
        - https://dolly.nais-dev-fss.adeo.no/login/oauth2/code/aad
        - https://dolly.dev.adeo.no/login/oauth2/code/aad
  replicas:
    min: 1
    max: 2
  port: 8080
  ingresses:
    - https://dolly.dev.intern.nav.no
    - https://dolly-frontend.dev.adeo.no
    - https://dolly.nais.preprod.local
    - https://dolly.nais-dev-fss.adeo.no
    - https://dolly.dev.adeo.no
  liveness:
    path: /internal/isAlive
    initialDelay: 20
    periodSeconds: 2
    failureThreshold: 140
  readiness:
    path: /internal/isReady
    initialDelay: 20
    periodSeconds: 2
    failureThreshold: 140
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    requests:
      cpu: 1000m
      memory: 1024Mi
    limits:
      cpu: 1500m
      memory: 2048Mi
  image: {{ image }}
  env:
    - name: TESTNORGE_MILJOER_SERVICE_CLIENT_ID
      value: 30003084-1585-4629-a017-686b4387b12e
    - name: TESTNORGE_PROFIL_API_CLIENT_ID
      value: e8e0772f-8204-4b88-88ad-233d62863f47
    - name: DOLLY_BACKEND_API_CLIENT_ID
      value: 787eb670-2731-49b4-8be1-2385990370a9
    - name: DOLLY_BACKEND_HOST
      value: https://dolly-backend.dev.adeo.no
    - name: TESTNORGE_MILJOER_SERVICE_HOST
      value: https://miljoer-service.dev.intern.nav.no
    - name: TESTNORGE_PROFIL_API_HOST
      value: https://testnorge-profil-api.dev.intern.nav.no
  vault:
    enabled: true
    paths:
      - kvPath: /kv/preprod/fss/dolly-frontend/dolly
        mountPath: /var/run/secrets/nais.io/vault
