spring:
  application:
    name: testnorge-bisys
    version: application.version.todo #TODO Finn ut hvordan denne kan settes fra gradle
    description: Testnorge-Bisys er adapteren mellom orkestratoren og bisys for opprettelse av syntetiske bistandsmeldinger.


management.endpoints.web.base-path: /internal
management.endpoints.web.exposure.include: prometheus

consumers:
  bidragsmelding:
    url: https://dummy.dev.adeo.no
  hodejegeren:
    url: https://testnorge-hodejegeren.dev.adeo.no/api
  synt-bisys:
    url: https://synthdata-bisys.dev.intern.nav.no
    cluster: dev-gcp
    namespace: dolly
    name: synthdata-bisys

AAD_ISSUER_URI: https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b

USE_HISTORICAL_MOTTATTDATO: 1
