spring:
  application:
    name: testnorge-bisys
    version: application.version.todo #TODO Finn ut hvordan denne kan settes fra gradle
    description: Testnorge-Bisys er adapteren mellom orkestratoren og bisys for opprettelse av syntetiske bistandsmeldinger.


management.endpoints.web.base-path: /internal
management.endpoints.web.exposure.include: prometheus
consumers.bidragsmelding.url: https://dummy.dev.adeo.no
SYNTREST_REST_API: https://syntrest.dev.adeo.no/api
HODEJEGEREN_REST_API: https://testnorge-hodejegeren.dev.adeo.no/api
USE_HISTORICAL_MOTTATTDATO: 1