application:
  version: application.version.todo #TODO Finn ut hvordan denne kan settes fra gradle
  name: testnorge-synt-arbeidsforhold-api

consumers:
  synt-arbeidsforhold:
    url: https://syntrest.nais.preprod.local
  arbeidsforhold:
    url: https://testnorge-arbeidsforhold-api.nais.preprod.local
  statiske-data-forvalter:
    url: https://testnorge-statisk-data-forvalter.nais.preprod.local
  kodeverk:
    url: https://kodeverk.nais.preprod.local