server.port: 8020

#dolly.url: http://localhost:8020/api/v1

#fagsystem.tpsf.url: https://tps-forvalteren-u2.nais.preprod.local

TESTNORGE_PROFIL_API_CLIENT_ID: f73bfcd0-a1f5-4d3f-bfb4-4d0361191438
DOLLY_BACKEND_API_CLIENT_ID: f0174d28-cb33-44f9-a7b5-09e52582e601

DOLLY_BACKEND_HOST: https://dolly-backend-dev.dev.adeo.no
TESTNORGE_PROFIL_API_HOST: https://testnorge-profil-api-dev.dev.intern.nav.no

zuul:
  debug:
    request: true
