AAD_ISSUER_URI: https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b
server:
  use-forward-headers: true

zuul:
  routes:
    dolly-backend:
      path: /api/v1/**
      url: ${DOLLY_BACKEND_HOST}/api/v1
      sensitiveHeaders: Cookie,Set-Cookie
    testnorge-profil-api:
      path: /api/testnorge-profil-api/**
      url: ${TESTNORGE_PROFIL_API_HOST}/api
      sensitiveHeaders: Cookie,Set-Cookie
    testnorge-varslinger-api:
      path: /api/testnorge-varslinger-api/**
      url: https://testnorge-varslinger-api.dev.adeo.no/api
      sensitiveHeaders: Cookie,Set-Cookie

applications:
  testnorge-profil-api: ${TESTNORGE_PROFIL_API_CLIENT_ID}
  dolly-backend: ${DOLLY_BACKEND_API_CLIENT_ID}
  testnorge-varslinger-api: a1dca941-bdd5-4705-a1a4-04cf76473040
  testnorge-tilbakemelding-api: 6554cc46-d5a9-4b9b-aafb-775b9ee09696


consumers:
  testnorge-tilbakemelding-api.baseUrl: https://testnorge-tilbakemelding-api.dev.adeo.no

spring:
  cloud:
    vault:
      enabled: false
  security:
    oauth2:
      client:
        registration:
          aad:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: openid, ${CLIENT_ID}/.default
        provider:
          aad:
            authorization-uri: ${AAD_ISSUER_URI}/oauth2/v2.0/authorize
            token-uri: ${AAD_ISSUER_URI}/oauth2/v2.0/token
            jwk-set-uri: ${AAD_ISSUER_URI}/discovery/v2.0/keys