AAD_ISSUER_URI: https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b
CLIENT_ID: c163301f-082d-4fbd-9a78-6bdd92e3c36a

#batch
spring:
  security:
    oauth2:
      resourceserver:
        aad:
          issuer-uri: ${AAD_ISSUER_URI}/v2.0
          jwk-set-uri: ${AAD_ISSUER_URI}/discovery/v2.0/keys
          accepted-audience: ${CLIENT_ID}, api://${CLIENT_ID}
        tokenx:
          issuer-uri: https://tokendings.dev-gcp.nais.io
          jwk-set-uri: https://tokendings.dev-gcp.nais.io/jwks
          accepted-audience: dev-gcp:dolly:testnav-adresse-service


batch:
  avspillergruppeId.miljoe: {100000883:"q2"}
  antallMeldingerPerEndringskode: {"0110":10,"0211":20}
  navMeldinger: {"Z010":0}

inntektbatch:
  avspillergruppeId: 100000445

poppbatch:
  antallNyeIdenter: 1

aaregbatch:
  antallNyeIdenter: 1

bisysbatch:
  antallNyeIdenter: 1

sambatch:
  antallMeldinger: 1

arenabatch:
  antallNyeIdenter: 1

frikortbatch:
  antallNyeIdenter: 1

medlbatch:
  prosentfaktor: 0.1

instbatch:
  avspillergruppeId: 100000445
  miljoe: t9
  antallNyeIdenter: 1

tpbatch:
  antallPersoner: 10000

ibm.mq.user-authentication-m-q-c-s-p: false
