fasit.enabled: false

server.port: 8020
dolly.url: http://localhost:8080/api/v1
#dolly.url: https://dolly-t2.nais.preprod.local/api/v1

# Used to refer to local development openAm client
freg.security.oidc.idp.openAm.clientId: ${idp.openAm.clientId}-localhost