apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dolly-backend-dev
  namespace: dolly
  labels:
    team: dolly
spec:
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: testnav-oversikt-frontend
          cluster: dev-gcp
        - application: dolly-frontend-dev
          cluster: dev-gcp
        - application: team-dolly-lokal-app
          cluster: dev-fss
        - application: app-1
          namespace: plattformsikkerhet
          cluster: dev-gcp
    outbound:
      rules:
        - application: testnav-helsepersonell-service
        - application: testnav-organisasjon-forvalter
        - application: testnav-inntektsmelding-service
        - application: testnav-tps-messaging-service
        - application: generer-navn-service
        - application: testnorge-profil-api-dev
        - application: testnav-person-service
        - application: testnav-inst-service
        - application: testnav-pdl-forvalter-dev
        - application: testnav-arbeidsforhold-service
        - application: testnav-amelding-service
        - application: testnav-organisasjon-service
        - application: testnav-synt-sykemelding-api
      external:
        - host: testnav-kodeverk-proxy.dev-fss-pub.nais.io
        - host: testnav-dokarkiv-proxy.dev-fss-pub.nais.io
        - host: testnav-brregstub-proxy.dev-fss-pub.nais.io
        - host: testnav-testnorge-aareg-proxy.dev-fss-pub.nais.io
        - host: testnav-krrstub-proxy.dev-fss-pub.nais.io
        - host: testnav-inntektstub-proxy.dev-fss-pub.nais.io
        - host: testnav-inst-service.dev.intern.nav.no
        - host: testnav-statisk-data-forvalter-proxy.dev-fss-pub.nais.io
        - host: testnav-skjermingsregister-proxy.dev-fss-pub.nais.io
        - host: testnav-arena-forvalteren-proxy.dev-fss-pub.nais.io
        - host: testnav-pdl-proxy.dev-fss-pub.nais.io
        - host: testnav-sigrunstub-proxy.dev-fss-pub.nais.io
        - host: testnav-pensjon-testdata-facade-proxy.dev-fss-pub.nais.io
        - host: testnav-sykemelding-api-proxy.dev-fss-pub.nais.io
        - host: tps-forvalteren-dev-proxy.dev-fss-pub.nais.io
        - host: testnav-udistub-proxy.dev-fss-pub.nais.io
        - host: testnav-kontoregister-person-proxy.dev-fss-pub.nais.io
  webproxy: true
  azure:
    application:
      enabled: true
      tenant: nav.no
  image: {{image}}
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
  replicas:
    min: 1
    max: 1
  port: 8080
  ingresses:
    - https://dolly-backend-dev.dev.intern.nav.no
  liveness:
    path: /internal/isAlive
    initialDelay: 20
    periodSeconds: 2
    failureThreshold: 140
  readiness:
    path: /internal/isReady
    initialDelay: 20
    periodSeconds: 2
    failureThreshold: 140
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    requests:
      cpu: 1000m
      memory: 1024Mi
    limits:
      cpu: 1500m
      memory: 2048Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        name: testnav-dolly-backend-dev
        databases:
          - name: testnav-dolly-backend-dev
        autoBackupTime: "01:00"
