
providers:
  tpsf:
    url: https://tps-forvalteren-u2.nais.preprod.local
#    url: http://localhost:8050

#spring:
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true