freg.security.oidc.idp.openAm:
  hostUrl: https://isso-t.adeo.no:443/isso
  issuerUrl: https://isso-t.adeo.no:443/isso/oauth2
  jwksUrl: https://isso-t.adeo.no/isso/oauth2/connect/jwk_uri

freg.security.oidc.idp.navSts:
  hostUrl: https://security-token-service-q4.nais.preprod.local
  issuerUrl: https://security-token-service-q4.nais.preprod.local
  jwksUrl: https://security-token-service-q4.nais.preprod.local/rest/v1/sts/jwks

### FREG-SECURITY ###
freg.security.oidc.enabled: true

providers:
  fasit:
    url: https://fasit.adeo.no
  tpsf:
    url: https://tps-forvalteren-u2.nais.preprod.local
#    url: http://localhost:8050
  sigrunstub:
    url: https://sigrun-skd-stub.nais.preprod.local
  krrstub:
    url: https://krr-stub.nais.preprod.local
  udistub:
    url: https://udi-stub.nais.preprod.local
  kodeverk:
    url: https://kodeverk.nais.preprod.local
  norg2:
    url: https://app-q1.adeo.no/norg2
  arenaForvalter:
    url: https://arena-forvalteren.nais.preprod.local
  pdlForvalter:
    url: https://person-testdata.nais.preprod.local
  personOppslag:
    url: https://person-oppslag.nais.preprod.local
  syntdata:
    url: https://syntrest.nais.preprod.local
  instdata:
    url: https://testnorge-inst.nais.preprod.local

fasit:
  url: https://fasit.adeo.no
  environment.name: t1

spring:
  flyway:
    enabled: false # Disabled by default as you should probably think twice before running Flyway-migrations

dolly.security.cors.origins: http://localhost:3050,http://localhost:3000,http://localhost:8020,http://localhost:8050