spring:
  application:
    name: hendelse-api
  flyway:
    locations: classpath:db/migration
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
application:
  version: application.version.todo #TODO Finn ut hvordan denne kan settes fra gradle
  name: testnorge-hendelse-api

kafka:
  bootstrapservers: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
  schemaregistryservers: http://kafka-schema-registry.tpa.svc.nais.local:8081
  groupid: testnorge-hendelse-api-v1
