application:
  version: application.version.todo #TODO Finn ut hvordan denne kan settes fra gradle
  name: rapportering-api

spring:
  application:
    name: testnorge-rapportering-api
  flyway:
    locations: classpath:db/migration
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

kafka:
  bootstrapservers: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
  schemaregistryservers: http://kafka-schema-registry.tpa.svc.nais.local:8081
  groupid: testnorge-rapportering-api-v1


consumer:
  slack:
    token: ${slack.token}
    baseUrl: https://slack.com
    channel: ${slack.channel}