CLIENT_SECRET: ${azure.app.client.secret}

app:
  db:
    flyway:
      role: testnorge-rapportering-admin
      backend: postgresql/preprod-fss/creds

spring:
  datasource:
    url: jdbc:postgresql://b27dbvl022.preprod.local:5432/testnorge-rapportering?useUnicode=yes&characterEncoding=UTF-8
    hikari:
      maximum-pool-size: 3
      minimum-idle: 0
  main:
    banner-mode: off