name: Deploy ident-pool-test

on:
  push:
    paths:
      - apps/ident-pool/**
      - libs/testnorge-core/**

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/ident-pool-test:${{ github.sha }}

jobs:
  build_and_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Compile
        env:
          GITHUB_USERNAME: token
          NAV_TOKEN: ${{ secrets.NAV_TOKEN }}
        run: ./gradlew :ident-pool-app:build

      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build --tag ${IMAGE} . -f ./apps/ident-pool/Dockerfile
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
      - name: Deploy to nais
        timeout-minutes: 5
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DOLLY_DEPLOY_API_KEY }}
          CLUSTER: dev-fss
          RESOURCE: apps/ident-pool/nais_dev-fss_test_template.yaml