name: Proxy statisk-data-forvalter-proxy

on:
  push:
    paths:
      - proxies/statisk-data-forvalter-proxy/**
      - libs/reactive-core/**
      - libs/reactive-proxy/**
      - .github/workflows/proxy.statisk-data-forvalter-proxy.yml

jobs:
  scan:
    name: Scan
    uses: navikt/testnorge/.github/workflows/common.sonar.yml@master
    with:
      working-directory: 'proxies/statisk-data-forvalter-proxy/'
    secrets:
      NAV_TOKEN: ${{ secrets.NAV_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  build:
    name: Build
    uses: navikt/testnorge/.github/workflows/common.build-and-publish.backend.yml@master
    if: ${{ github.ref == 'refs/heads/master' }}
    with:
      working-directory: 'proxies/statisk-data-forvalter-proxy/'
      app-name: 'statisk-data-forvalter-proxy'
    secrets:
      NAV_TOKEN: ${{ secrets.NAV_TOKEN }}
  deploy-dev:
    name: Deploy
    uses: navikt/testnorge/.github/workflows/common.deploy.yml@master
    needs: build
    if: ${{ github.ref == 'refs/heads/master' }}
    with:
      resource: 'proxies/statisk-data-forvalter-proxy/config.yml'
      app-name: 'statisk-data-forvalter-proxy'
      cluster: 'dev-fss'
    secrets:
      API_KEY: ${{ secrets.NAIS_DOLLY_DEPLOY_API_KEY }}