spring.application:
  version: application.version.todo #TODO Finn ut hvordan denne kan settes fra gradle
  name: testnorge-synt-person-api
  desciption: API for opprettelse av syntetiske personer

consumers.syntrest.url: https://syntrest.dev.adeo.no/api
consumers.identpool.url: https://ident-pool.dev.adeo.no/api

consumers.personapi:
  url: ${PERSON_API_URL}
  client_id: ${PERSON_API_CLIENT_ID}
  client_secret: ${PERSON_API_CLIENT_SECRET}

AAD_ISSUER_URI: https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b